name: Diff-Report

on: 
  pull_request:
  issue_comment:
    types: [created]

jobs:
  make_report:
    env:
      pr_body: ${{ github.event.pull_request.body }}
    runs-on: ubuntu-latest

    steps:
     - name: print variable
       run: |
        echo "${{env.pr_body}}" > text
        grep "^Diff Regression projects:" text > temp
        sed 's/Diff Regression projects: //' temp > proj
        grep "^Diff Regression config:" text > temp
        sed 's/Diff Regression config: //' temp > config
        cat proj
        cat config
        wget -q -i proj -O proj.pro
        wget -q -i config -O config.xml
        ls -la
#    - name: Checkout
#      uses: actions/checkout@v1
      
#     - name: Comment PR
#       uses:  kate2513/javascript-test-action@master 
#       with:
#        message: 'Example of message!'
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
