name: Diff-Report

on: 
  pull_request:
  issue_comment:
    types: [created]

jobs:
  make_report:
    env:
      pr_body: ${{ github.event.pull_request.body }}
    runs-on: ubuntu-latest

    steps:
     - name: print variable
       run: |
        echo "${{env.pr_body}}" > text
        ls -la
        cat text

#    - name: Checkout
#      uses: actions/checkout@v1
      
#     - name: Comment PR
#       uses:  kate2513/javascript-test-action@master 
#       with:
#        message: 'Example of message!'
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
