name: Diff-Report

on: 
  pull_request:
    types: [opened, reopened, synchronize, edited]
  issue_comment:
    types: [created]
env:
  pr_body: ${{ github.event.pull_request.body }}
  issue_body: ${{github.event.issue.body}}

jobs:
  Check-if-needed:
    runs-on: ubuntu-latest

    steps:        
     - name: Check message
       if: github.event_name == 'issue_comment'
       env:
         comment: ${{ toJson(github.event.issue)}}
       run: |
        echo "${{env.comment}}" 
  
  Get-Body:
    needs: [Check-if-needed]
    runs-on: ubuntu-latest
    steps:
      - name: Issue Body
        if: github.event_name == 'issue_comment'
        run: |
         echo "${{env.issue_body}}" > text
         cat text
         
      - name: PR body
        if: github.event_name == 'pull_request' 
        run: |
         echo "${{env.pr_body}}" > text
         cat text
         
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: something
        run: cat text
