name: Diff-Report
#123
on: 
  pull_request:
    types: [opened, reopened, synchronize, edited]
  issue_comment:
    types: [created]
env:
  pr_body: ${{ github.event.pull_request.body }}
  issue_body: ${{github.event.issue.body}}

jobs:
  make_report:
    if: (github.event_name == 'pull_request') || (github.event_name == 'issue_comment' && github.event.comment.body == 'report')
    runs-on: ubuntu-latest

    steps:        
     - name: Get issue body
       if: github.event_name == 'issue_comment'
       run: echo "${{env.issue_body}}" > text
       
     - name: Get PR body
       if: github.event_name == 'pull_request'
       run: echo "${{env.pr_body}}" > text
     
     - name: show info
       run: echo "${{toJSON(github.event)}}"
