name: Diff-Report

on: 
  pull_request:
    types: [opened, reopened, synchronize, edited]
  issue_comment:
    types: [created]


jobs:
  job1:
    if: github.event_name == 'pull_request'
    env:
     pr_body: ${{ github.event.pull_request.body }}  
    runs-on: ubuntu-latest

    steps:        
     - name: Get body
       run: |
        echo "${{env.pr_body}}" > text
        cat text
  
  job2:
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    env:
      issue_body: ${{github.event.issue.body}}
    steps:
      - name: Issue body
        run: |
         echo "${{env.issue_body}}" > text
         cat text
  job3:
    needs: [job1,job2]
    runs-on: ubuntu-latest
    steps:
      - name: something
        run: cat text
